web:
  image: nginx:1.12
  ports:
    - "8082:80"
  volumes:
    - ./code:/code
    - ./nginx.conf/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - ./code:/code

