web:
  image: nginx:latest
  ports:
    - "8081:80"
  volumes:
    - .:/content
    - ./nginx.conf/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - .:/content

