web:
  image: nginx:1.12
  ports:
    - "8081:80"
  volumes:
    - .:/content
    - ./nginx.conf/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - .:/content
  links:
    - db

db:
  image: mariadb:10.1
  volumes:
  - ./install/maria:/dockermaria/maria
  ports:
    - 3308:3306
  environment: 
    MYSQL_ROOT_PASSWORD: azerty