CREATE DATABASE IF NOT EXISTS db;
USE db;
CREATE TABLE IF NOT EXISTS matable (compteur INTEGER);
USE mysql;
GRANT ALL PRIVILEGES ON *.* TO 'php_user'@'%' IDENTIFIED BY 'sdrugntqqsciur';
FLUSH PRIVILEGES;